### ISSUE TITLE
equalTo with pointer field and objectId

### ISSUE THREAD

**Issue by kay-is** [ParsePlatform/ParseReact#93] opened 2015-07-11 22:23 UTC
I'm using the react-router and have a one-to-many relationship, which I realized with pointers.

When I navigate to the component, that should display the children, this component gets an ID (objectId) from the react-router as dynamic URL segment. The component doesn't have the parent object, so I tried to query with `Parse.Query('Child').equalsTo('parent', parentId)`, but since `parent` is a pointer field, Parse throws an error.

Is there a way to query all items that have the same parent pointer with the parents ID?

**Comment by mikemintz** [comment] 2015-07-12 01:34
Try:

```js
var Parent = Parse.Object.extend('Parent'); // or whatever you call the class

var query = Parse.Query('Child').equalsTo('parent', new Parent({id: parentId}))
```

**Comment by kay-is** [comment] 2015-07-13 12:49
Thank you :)

But this seems like a hack. Also, getting the ID from an object also felt like a hack, because ID was an object too, which contained the object type and the ID.

If I have, for example, an URL to the comments of a article, I want to either load all the comments with the article-ID (which is in the URL) or I want to load the article with all its comments. But since the article doesn't know anything about the comments that are related to it (the comments have a pointer to the article, but the article has no pointers to the comments) I can't simply query everything at once. I guess? Or am I missing something?.

**Comment by andrewimm** [comment] 2015-07-13 18:42
I'm closing this because it's an issue with the Parse JS SDK, and not Parse+React. Regardless, this is by design, since there's no way to tell the difference between a string and an object id. Before issuing a query, we don't necessarily know the schema of `Child`, which prevents us from providing insights into whether we should prematurely convert an object id string into a pointer reference.

As @mikemintz pointed out, you can create an empty object with a single pointer. That's the prescribed behavior here, since you're really saying "I want rows where the pointer references this object" vs "I want rows where the value is this string."
You can save typing by doing this, as well:
```js
new Parse.Query('Child').equalTo('parent', new Parse.Object('Parent', { id: parentId })
```

**Closed by andrewimm** 2015-07-13 18:42 UTC

**Comment by alfonsoolavarria** [comment] 2017-05-02 23:06
Funciona muy bien gracias @andrewimm
